import Testing
import SwiftData
import Foundation
@testable import Hosty

@Suite("HostEntry Tests")
struct HostEntryTests {

    @Test("HostEntry should format enabled entry correctly")
    func formattedEntryEnabled() {
        let entry = HostEntry(
            ipAddress: "127.0.0.1",
            domains: ["localhost.dev", "app.local"],
            isEnabled: true
        )

        #expect(entry.formattedEntry == "127.0.0.1\tlocalhost.dev app.local")
    }

    @Test("HostEntry should format disabled entry with comment prefix")
    func formattedEntryDisabled() {
        let entry = HostEntry(
            ipAddress: "192.168.1.100",
            domains: ["api.local"],
            isEnabled: false
        )

        #expect(entry.formattedEntry == "# 192.168.1.100\tapi.local")
    }

    @Test("HostEntry should include comment when present")
    func formattedEntryWithComment() {
        let entry = HostEntry(
            ipAddress: "127.0.0.1",
            domains: ["test.local"],
            isEnabled: true,
            comment: "Test server"
        )

        #expect(entry.formattedEntry == "127.0.0.1\ttest.local # Test server")
    }

    @Test("HostEntry should join multiple domains with space")
    func multipleDomains() {
        let entry = HostEntry(
            ipAddress: "127.0.0.1",
            domains: ["tenant1.local", "tenant2.local", "tenant3.local"],
            isEnabled: true
        )

        #expect(entry.formattedEntry == "127.0.0.1\ttenant1.local tenant2.local tenant3.local")
    }

    @Test("HostEntry should mark system entries correctly")
    func systemEntryDetection() {
        let localhost = HostEntry(
            ipAddress: "127.0.0.1",
            domains: ["localhost"],
            isSystemEntry: true
        )
        #expect(localhost.isSystemEntry == true)

        let broadcasthost = HostEntry(
            ipAddress: "255.255.255.255",
            domains: ["broadcasthost"],
            isSystemEntry: true
        )
        #expect(broadcasthost.isSystemEntry == true)

        let customEntry = HostEntry(
            ipAddress: "192.168.1.1",
            domains: ["custom.local"],
            isSystemEntry: false
        )
        #expect(customEntry.isSystemEntry == false)
    }
}

@Suite("HostProfile Tests")
struct HostProfileTests {

    @Test("HostProfile should generate hosts file with system entries")
    func generateHostsFileContent() throws {
        let config = ModelConfiguration(isStoredInMemoryOnly: true)
        let container = try ModelContainer(for: HostProfile.self, HostEntry.self, configurations: config)

        let profile = HostProfile(name: "Test Profile")
        let entry = HostEntry(
            ipAddress: "127.0.0.1",
            domains: ["test.local"],
            isEnabled: true
        )
        entry.profile = profile
        profile.entries.append(entry)

        let content = profile.generateHostsFileContent()

        #expect(content.contains("# Generated by Hosty - Profile: Test Profile"))
        #expect(content.contains("127.0.0.1\tlocalhost"))
        #expect(content.contains("255.255.255.255\tbroadcasthost"))
        #expect(content.contains("::1\tlocalhost"))
        #expect(content.contains("127.0.0.1\ttest.local"))
    }

    @Test("HostProfile should skip system entries in custom section")
    func skipSystemEntriesInCustomSection() throws {
        let config = ModelConfiguration(isStoredInMemoryOnly: true)
        let container = try ModelContainer(for: HostProfile.self, HostEntry.self, configurations: config)

        let profile = HostProfile(name: "Test Profile")

        let systemEntry = HostEntry(
            ipAddress: "127.0.0.1",
            domains: ["localhost"],
            isEnabled: true,
            isSystemEntry: true
        )
        systemEntry.profile = profile
        profile.entries.append(systemEntry)

        let customEntry = HostEntry(
            ipAddress: "192.168.1.1",
            domains: ["custom.local"],
            isEnabled: true,
            isSystemEntry: false
        )
        customEntry.profile = profile
        profile.entries.append(customEntry)

        let content = profile.generateHostsFileContent()
        let lines = content.components(separatedBy: .newlines)
        let customSectionStartIndex = lines.firstIndex(where: { $0.contains("# Custom entries") }) ?? 0
        let customSectionLines = lines[customSectionStartIndex...]

        let duplicateLocalhost = customSectionLines.contains(where: {
            $0.contains("127.0.0.1") && $0.contains("localhost") && !$0.hasPrefix("#")
        })

        #expect(duplicateLocalhost == false)
        #expect(content.contains("192.168.1.1\tcustom.local"))
    }

    @Test("HostProfile should include disabled entries as comments")
    func disabledEntriesAsComments() throws {
        let config = ModelConfiguration(isStoredInMemoryOnly: true)
        let container = try ModelContainer(for: HostProfile.self, HostEntry.self, configurations: config)

        let profile = HostProfile(name: "Test Profile")
        let disabledEntry = HostEntry(
            ipAddress: "192.168.1.100",
            domains: ["disabled.local"],
            isEnabled: false
        )
        disabledEntry.profile = profile
        profile.entries.append(disabledEntry)

        let content = profile.generateHostsFileContent()

        #expect(content.contains("# Disabled entries"))
        #expect(content.contains("# 192.168.1.100\tdisabled.local"))
    }

    @Test("HostProfile should set timestamps on creation")
    func profileTimestamps() {
        let profile = HostProfile(name: "Test Profile")

        #expect(profile.createdAt <= Date())
        #expect(profile.updatedAt <= Date())
        #expect(profile.createdAt == profile.updatedAt)
    }

    @Test("HostProfile should have empty entries on creation")
    func emptyEntriesOnCreation() {
        let profile = HostProfile(name: "Test Profile")

        #expect(profile.entries.isEmpty)
    }
}

@Suite("HostsManager Tests")
struct HostsManagerTests {

    @Test("HostsManager should be singleton")
    func singletonInstance() {
        let instance1 = HostsManager.shared
        let instance2 = HostsManager.shared

        #expect(instance1 === instance2)
    }
}
