
import Foundation
import SwiftData

@Model
final class HostProfile {
    var id: UUID
    var name: String
    var isActive: Bool
    var createdAt: Date
    var updatedAt: Date

    @Relationship(deleteRule: .cascade, inverse: \HostEntry.profile)
    var entries: [HostEntry]

    init(name: String, isActive: Bool = false) {
        self.id = UUID()
        self.name = name
        self.isActive = isActive
        self.createdAt = Date()
        self.updatedAt = Date()
        self.entries = []
    }

    func generateHostsFileContent() -> String {
        var content = "# Generated by Hosty - Profile: \(name)\n"
        content += "# Updated: \(updatedAt.formatted())\n\n"

        content += "##\n"
        content += "# Host Database\n"
        content += "#\n"
        content += "# localhost is used to configure the loopback interface\n"
        content += "# when the system is booting. Do not change this entry.\n"
        content += "##\n"
        content += "127.0.0.1\tlocalhost\n"
        content += "255.255.255.255\tbroadcasthost\n"
        content += "::1\tlocalhost\n\n"

        content += "# Custom entries from profile: \(name)\n"
        for entry in entries where entry.isEnabled && !entry.isSystemEntry {
            content += entry.formattedEntry + "\n"
        }

        let disabledEntries = entries.filter { !$0.isEnabled && !$0.isSystemEntry }
        if !disabledEntries.isEmpty {
            content += "\n# Disabled entries\n"
            for entry in disabledEntries {
                content += entry.formattedEntry + "\n"
            }
        }

        return content
    }
}
